"Apparently this is basic:
set number
syntax on
syntax enable
filetype plugin on
filetype plugin indent on
filetype on
filetype indent on

"Where am I?
set ruler

"What am I doing?
set showmode

"What year is this?
set nocompatible

"Proper Backspace behavior
set backspace=2

"Modelines are historically insecure
set nomodeline

set t_Co=256

set path+=**

set wildmenu

"Slant made me set my leader key to Space! Is that... wise?
let mapleader = " "

"For modifiying my .vimrc a lot
nmap <Leader>v :source $MYVIMRC<CR>
nmap <Leader>V :e ~/.vim/vimrc<CR>

"Give me NERDTree!
nmap <Leader>N :NERDTree<CR>

"Vim-test
let test#strategy = "dispatch"
nmap <silent> <Leader>t :TestNearest<CR>
nmap <silent> <Leader>T :TestFile<CR>
nmap <silent> <Leader>a :TestSuite<CR>
nmap <silent> <Leader>l :TestLast<CR>
nmap <silent> <Leader>g :TestVisit<CR>

"Execute tests
nmap <F9> :!clear<CR>:!rails test<CR>

"git with fugitive
nmap <Leader>gs :Gstatus<CR>

"reverse selection
vmap <Leader>fR c<C-O>:set ri<CR><C-R>"<Esc>:set nori<CR>

let g:user_emmet_leader_key = '<C-y>'
set backupcopy=yes
autocmd BufNewFile,BufRead *.twig set syntax=html

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"

"Insert timestamp
nmap <Leader>d :put =strftime('%c')<CR>


nmap <Leader>irb :!clear<CR>:!irb<CR>
nmap <Leader>rcw :!ruby -cw %<CR>
nmap <Leader>esc :!/usr/bin/setxkbmap -option "caps:swapescape"<CR>

nmap <Leader>f :FZF<CR>
nmap <F12> :!ruby %<CR>

nmap <Leader>w :e ~/notes/technomancy.md<CR>
nmap <Leader>e :e ~/notes/wtf.md<CR>
nmap <Leader>r :e ~/notes/ricing.md<CR>

nmap <Leader>1 iThis is Hotkey number ONE!!<CR><ESC>
nmap <Leader><F4> iThis works.<CR><ESC>
nmap <Leader>Tt iThis works.<CR><ESC>



autocmd FileType ruby setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType eruby setlocal expandtab shiftwidth=2 tabstop=2
